### ISSUE TITLE
In vital pressing control is supposed to allow fine tuning. In vitalium it brings up value editor.

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/DISTRHO-Ports#112]
It is kind of frustrating that there is not way to fine tune a parameter in vitalium.

**Comment by falkTX** [comment]
shift key?

**Comment by TheGuyWhoo** [comment]
Shift has no effect.

**Comment by DarkRTA** [comment]
I built upstream from source and managed to confirm that Vitalium actually has a bug here. Control + Left Click fine tunes the control in upstream Vital but opens the value editor in Vitalium. You also can't seem to open the skin designer by Alt+Clicking on the 3 lines menu next to the preset selector. Its like the Alt key does nothing and the Control key now acts as the Alt key.

**Comment by DarkRTA** [comment]
this is caused by https://github.com/DISTRHO/DISTRHO-Ports/commit/d83e00f4af9297863dbe68c7eb4c9ff7282fdda4 causing key conflicts
