### ISSUE TITLE
Ardour 4.4 fails to load KlangFalter and Vex plugins

### ISSUE THREAD

**Issue by Fak3** [DISTRHO/DISTRHO-Ports#12]
Error message in the log window:

```
[WARNING]: Ignoring LV2 plugin "KlangFalter" because its buffer-size requirements cannot be satisfied.
[WARNING]: Ignoring LV2 plugin "Vex" because its buffer-size requirements cannot be satisfied.
```

**Comment by falkTX** [comment]
That's completely intentional.
Those 2 plugins don't work well with variable buffer sizes right now, they need some work and testing.

**Comment by trebmuh** [comment]
Still the same with Ardour 5.12.

@falkTX just to be clear (you added a wontfix label and a future one), your current plan is: you're not willing to do the job yourself but ou're happy if someone submit a PR or you're planning to do that yourself in the future?

**Comment by falkTX** [comment]
talk with upstream klangfalter and see what he says.
afaik making it work with non-fixed buffer sizes is not trivial.
I don't plan to work on this myself.

**Comment by trebmuh** [comment]
Thanks for the answer @falkTX .
I've reported that to upstream.

**Comment by trebmuh** [comment]
See https://github.com/DISTRHO/DISTRHO-Ports/issues/6 as well.

**Comment by sub26nico** [comment]
Using Klangfalter works well in Carla (as standalone app or lv2 in Ardour), 
but you have to give the IR's path in the settings of Klangfalter. And Klangfalter can 
reloads the IRs and shows the wave form. If the Ir loaded is not in the path given in the settings, 
Klangfalter doesn't reload the IR and can't show the waveform once the IR loaded.

**Comment by falkTX** [comment]
you're bypassing the issue and the reason why the plugin is disabled for ardour.
dont be mad if you get crashes while using it...

**Comment by falkTX** [comment]
One ticket per issue, this one being about requirement of fixed buffer-size.
I decided against doing the work to support variable buffer size for these plugins. There are other plugins out there that do similar things, so if using a host that cannot do fixed buffer-size, just find different plugins.
