### ISSUE TITLE
obxd vsts

### ISSUE THREAD

**Issue by Paree24** [DISTRHO/DISTRHO-Ports#121]
Hi, i just read the whole stuff that happened with obxd on kvr and i read that you were planning to release a truly “free and open” version of it for all platforms. Is it still on the cards?

(Please feel free to close this issue if this is not the place to ask)

**Comment by falkTX** [comment]
there is already an obxd included in the project, just a bit outdated
and there is a ticket for updating obxd already https://github.com/DISTRHO/DISTRHO-Ports/issues/49
