### ISSUE TITLE
Stereo Source Separator link got DMCA'ded

### ISSUE THREAD

**Issue by j3bx** [DISTRHO/DISTRHO-Ports#124]
Licensing problems with the Steinberg SDK
https://github.com/laixinyuan/StereoSourceSepartion

**Comment by falkTX** [comment]
that was because of violations of the VST2 SDK, they do not allow other folks to reshare it.
the DISTRHO-Ports stuff makes use of the old JUCE-created GPLv3+ licensed VST2-compatible interface.
Steinberg does not own that one, so the repo wont be taken down.

**Comment by j3bx** [comment]
I see, thanks for the info
