### ISSUE TITLE
drumsynth: feature request: stereo

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/DISTRHO-Ports#14]
Noise based snares and HHs sound awesome when in stereo.

To get this, you currently have to make a copy of the track plus instrument, and pan them L an R.
It woud be very handy to have this built in.

I realise this would double the DSP load, but imho that's worth it.

**Comment by falkTX** [comment]
feel free to try to implement this yourself, but I won't do any drumsynth updates besides bugfixing.
you can also ask to the original author's project here - https://github.com/kunitoki/juced, although project has a very old juce version.

**Comment by magnetophon** [comment]
Thanks for the quick reply.
Kinda expected this, but it was worth a try.
I'll try upstream.  :)

**Comment by falkTX** [comment]
I am closing this issue. upstream is doing nothing with the plugins, and I only plan on doing bugfixes.
So better to close it as to not leave the impression this will ever happen
