### ISSUE TITLE
Dexed doesn't honor pitch bend with MIDI channel <> 1

### ISSUE THREAD

**Issue by suedwestlicht** [DISTRHO/DISTRHO-Ports#20]
When I place Dexed into a Qtractor MIDI track with a MIDI channel other than 1 then it doesn't honor pitch bend.

Workaround: place midifilter's midi channel map plugin before Dexed and change all incoming data to channel 1.

**Comment by falkTX** [comment]
Dexed has been updated, upstream had some changes.
Please check if this is still an issue or not. Thank you.

**Comment by suedwestlicht** [comment]
Generate ttl data for './TAL-Filter.so', basename: 'TAL-Filter'
Writing manifest.ttl... done!
Writing TAL-Filter.ttl... done!
Writing presets.ttl...
Saving preset 1/11...
Saving preset 2/11...
Saving preset 3/11...
Saving preset 4/11...
Saving preset 5/11...
Saving preset 6/11...
Saving preset 7/11...
Saving preset 8/11...
Saving preset 9/11...
Saving preset 10/11... done!
Generate ttl data for './Dexed.so', basename: 'Dexed'
./scripts/generate-ttl.sh: Zeile 27: 12909 Speicherzugriffsfehler  $GEN ./$FILE

**Comment by falkTX** [comment]
That crash on ttl generation has been fixed now

**Comment by suedwestlicht** [comment]
Yes, the "make lv2; make install" was successful.

The MIDI issue hasn't been fixed yet.

Unfortunately the parms have changed so Dexed didn't make a sound when I loaded a Qtractor session saved with a Dexed from a DISTRHO version from 2017-06-01. It remembered the chosen cartdridge/sound but I had to click on the sound again to make it work.  Saving the Qtractor session shows that a lot has changed internally. Maybe the upstream isn't aware that backwards compatibility is important.

**Comment by falkTX** [comment]
I think the pitchbend has been fixed upstream, their changelog mentions something about it.
I updated the included source.
Hopefully there is not another compatibility issue again...
Please update and test when you can.

**Comment by suedwestlicht** [comment]
Pitchbend is fixed. Couldn't detect another issue. Thank you.

**Comment by falkTX** [comment]
Good to know, closing the issue now.
