### ISSUE TITLE
Klangfalter's Autogain button doesn't work anymore

### ISSUE THREAD

**Issue by suedwestlicht** [DISTRHO/DISTRHO-Ports#22]
In Klangfalter from DISTRHO-Ports 2016-04-17 the GUI's autogain button could be toggled on and off. When switched off no autogain was applied. I have a source tree from 2017-06-01 where it's already broken. In recent sources it's still broken. Klicking on the button does nothing.

**Comment by falkTX** [comment]
This was removed on purpose by me, as it did not work as expected.
consider it to be just a label now.

**Comment by suedwestlicht** [comment]
OK. But the behaviour in Qtractor is strange:

- Autogain is set when activating the plugin. I hear the effect and a negative value is displayed on the GUI button. The value on Qtractor's "properties"-editor "Autogain" is still on 0.833 (=0 dB). So that display is wrong. But when I change 0.833 a bit back and forth to 0.833 again, then the GUI button displays 0.0dB and the audible setting is indeed 0.0dB.

- Leaving autogain at the negative value after activating of the plugin, saving the song in Qtractor and loading it sets autogain to 0.0dB. So Autogain isn't remembered. This behaviour of Qtractor/Klangfalter didn't change for years.

So I'd prefer to remove setting the autogain to a negative value after activating completely.
- It's not remembered across song's save/load
- It's not correctly handled regarding being displayed on Qtractor's builtin properties editor

What do you think?

**Comment by falkTX** [comment]
First I need to know if you're referring to the old or the new version (I assume new?) and what format - lv2 or vst?
autogain is not remembered, it's not a real parameter anymore but just a label for the gui.

**Comment by suedwestlicht** [comment]
I use recent klangfalter.lv2

Yep, autogain is not remembered BUT it's "halfway" applied when klangfalter.lv2 is activated in Qtractor. Then the wet signal is lower in volume as displayed on the GUI's button.

This setting isn't transferred to the settings I can edit with Qtractor's internal plugin's properties dialog. That's probably the cause why it's not restored when saving/reloading a qtr-file.

So my proposed change is:
Don't lower the volume when the plugin is activated. There must be some piece of code that's executed when klangfalter.lv2 is acivated (but not when it's loaded by Qtractore automatically when loading a qtr-file). This code seems to change autogain and should be deleted.

**Comment by suedwestlicht** [comment]
The same happens when I change the endpoint of an impulse response. Autogain immediately jumps to a negative value.

**Comment by falkTX** [comment]
Fixed with the last 2 commits.
