### ISSUE TITLE
4 links seems broken

### ISSUE THREAD

**Issue by trebmuh** [DISTRHO/DISTRHO-Ports#24]
I don't know if it on purposes or not. The 4 following links seems broken since they're pointing to non-existing files:
```
ports/tal-reverb/LV2/InterpolatorLinear.h
ports/tal-reverb/VST/InterpolatorLinear.h
ports/tal-reverb-2/LV2/InterpolatorLinear.h
ports/tal-reverb-2/VST/InterpolatorLinear.h
```

**Comment by falkTX** [comment]
The links were actually correct, but I removed the need for them now anyway.
