### ISSUE TITLE
OBXD : MIDI learn?

### ISSUE THREAD

**Issue by trebmuh** [DISTRHO/DISTRHO-Ports#30]
Is OBXD having a MIDI learn feature? (to assign its GUI control buttons to a MIDI material)

Something could be half-baked here since there is a placeholder for a "LEARN" functionality in the "Manual" section, but there is no button:

![distrho-ports-obxd-prez](https://user-images.githubusercontent.com/8705846/50398926-c17bd200-077b-11e9-9f78-ffd17606f4a0.png)

**Comment by falkTX** [comment]
The official version does, my ported version does not - intentionally.
MIDI learn on the plugin side is something that breaks parameter automation, and it is not allowed by design in LV2 (plugins that do it might end up with undefined state)
When I port plugins I make sure to remove such functionality.

So, it is working as intended.
Thanks for asking though

**Comment by trebmuh** [comment]
Correct me if I'm wrong, if I understand it right, you removed the MIDI learn feature from it to be able to use the host parameter automation. Then, one may be able to use the host MIDI-learn feature to achieve MIDI control of the Obxd GUI parameters. Is that right?

**Comment by falkTX** [comment]
You can still use both plugin and host-side midi learn on the official version, but there is a chance of conflicts.
I removed things that break the LV2 spec.
I think plugin-side automation (when running inside a daw) is a terrible idea

You can use host-side "MIDI learn" to automate parameters yes.
I know at least Ardour can do this.
Carla can automate the parameters with MIDI CC too, but it lacks the learn functionality

**Comment by trebmuh** [comment]
Thank you for this complete answer @falkTX 
Merry Christmas to you and yours.

**Comment by falkTX** [comment]
No problem
Merry Christmas to you too
