### ISSUE TITLE
A plugins-suite candidat for DPF maybe?

### ISSUE THREAD

**Issue by trebmuh** [DISTRHO/DISTRHO-Ports#33]
https://github.com/bdejong/smartelectronix

**Comment by falkTX** [comment]
Great find, I did not know of these plugins!
They require a CLA for any changes though, not happy with tbh.

I left a question for them at https://github.com/bdejong/smartelectronix/issues/44

**Comment by trebmuh** [comment]
Nice to see that you are interested. To be totally honest, I didn't know about those until today when @jpcima told me about those.

**Comment by falkTX** [comment]
I added this to https://github.com/DISTRHO/DISTRHO-Ports/wiki/Possible-Ports
closing ticket since it is not a bug, it is better to keep tickets for bugs only.
we can use that wiki page to reference possible plugin ports.
