### ISSUE TITLE
Some LV2 plugins do not have a URI

### ISSUE THREAD

**Issue by dvzrv** [DISTRHO/DISTRHO-Ports#59]
Hi! when packaging distrho-ports 2020.07.14 for Arch Linux I realized, that a few of the plugins do not have a real URI set:

```
urn:juce:TalDub3
urn:juce:TalFilter
urn:juce:TalFilter2
urn:juce:TalReverb
urn:juce:TalReverb2
urn:juce:TalReverb3
urn:juce:Vex
urn:juced:DrumSynth
urn:juced:EQinox
```

Is this intentional or accidental? Is it valid to use those? I see that e.g. zamaudio does this, too.

For ambix I have provided a fix to add real URIs (https://github.com/kronihias/ambix/pull/28).

**Comment by falkTX** [comment]
This is fine and completely valid. Those plugins did not have its own page back then (perhaps still dont) so I just used a more generic looking URI.
