### ISSUE TITLE
Chow does not show GUI (LV2, Linux)

### ISSUE THREAD

**Issue by flos-audio-plugins** [DISTRHO/DISTRHO-Ports#64]
Hi there,

on Linux I have an issue with the LV2 version of the CHOW plugin: The Audio Processor starts normally, but the GUI never comes up since the plugin's `createEditor()` function never gets called.
I could narrow this issue down to the juce_LV2_Wrapper.cpp, line 1567:
`ui = std::make_unique<JuceLv2UIWrapper> (filter.get(), writeFunction, controller, widget, features, isExternal);`
This function call never returns and apparently runs into to some kind of dead lock, I guess. 

All other LV2 plugins of the DISTRO Ports seem to use juce-legacy (based on Juce 5 I guess) instead of juce-current and they run fine for me. I have a similar issue with my own plugins: No GUI when using the latest Juce fork from DISTRHO, but they previously worked fine with Juce 5 and your LV2 modifcations.

Tested on ArchLinux and on a fresh Debian 10 using jalv (and partly carla & ardour).

**Comment by flos-audio-plugins** [comment]
Might be related to https://github.com/jatinchowdhury18/JUCE/commit/967b46532b9a470b35784346dd2edbb22e943714#.

**Comment by falkTX** [comment]
This was fixed a few commits ago, some needed fixes to lv2 wrapper have been done.
