### ISSUE TITLE
dragging corner of Vitalium window resizes contents but not the window

### ISSUE THREAD

**Issue by Be-ing** [DISTRHO/DISTRHO-Ports#65]
This makes it difficult to use on high DPI screens:
![image](https://user-images.githubusercontent.com/9455094/109539424-eae4c680-7a86-11eb-9e27-ce7625a82a18.png)
![image](https://user-images.githubusercontent.com/9455094/109539559-123b9380-7a87-11eb-95cf-763816e67bf6.png)

**Comment by falkTX** [comment]
this depends on the host and plugin format used.

works correctly with lv2 and carla.

**Comment by Be-ing** [comment]
This was with LV2 in Ardour. I couldn't get the plugin to be detected in Carla, but I'll try that again...

**Comment by falkTX** [comment]
I can reproduce in jalv, let me try something quick..

**Comment by Be-ing** [comment]
I confirm this bug is fixed. Thank you, good work!
