### ISSUE TITLE
Vitalium: The menu items regarding soundbanks/presets don't do anything

### ISSUE THREAD

**Issue by aki-k** [DISTRHO/DISTRHO-Ports#72]
These items on the right side of the top preset selection don't do anything:

"open external preset" and "import bank"

I have both zenity and kdialog installed on Ubuntu Mate 18.04.

I also downloaded the free Echo Sound Works wavetables from [https://www.echosoundworks.com/eswcorewavetables](https://www.echosoundworks.com/eswcorewavetables) but couldn't figure out the correct directory to put them in. I tried unpacking them to ~/.local/share/vital but didn't know how to make it work.

**Comment by falkTX** [comment]
Put them in ~/.local/share/vitalium

weirdly, the dialogs open fine here in 20.04

**Comment by aki-k** [comment]
I unpacked the zip archive file "Echo Sound Works Core Tables.zip" into ~/.local/share/vitalium and it created a directory "~/.local/share/vitalium/Echo Sound Works Core Tables". Still the Vitalium preset browser doesn't show any presets or wavetables. Are they somewhere else in the Vitalium GUI?

**Comment by falkTX** [comment]
hmm no, but there might be some other config needed to activate these presets.
when I copied the vital folder into vitalium, I could then see all of the presets.

I am not familiar enough with how this works internally to be able to help here.

**Comment by aki-k** [comment]
Ok that worked for me too.

```
rm -rf ~/.local/share/vitalium
mv ~/.local/share/vital ~/.local/share/vitalium
```
I can try to find which file it's looking for.

**Comment by aki-k** [comment]
The original problem is still there. I can't use these two menu functions, "open external preset" and "import bank".

**Comment by aki-k** [comment]
I noticed that taylordotfish's version is able to open the file requestor. Maybe it's just a matter of how you open it, with xdg-open or however?

**Comment by Scrambler70** [comment]
ah! Regarding the import of the files...This is probably because that particular repo (https://www.echosoundworks.com/eswcorewavetables) isn't actually Vital Presets. They are WAV audio files. in Vitalium, you can add a folder location for the wavetables if you right click on Init wavetable, and select add folder. Choose the top folder of your wavetable directory, and boom, you have access to all of the wavetables you downloaded.
