### ISSUE TITLE
Vitalium: The whole Xorg locks up after using Vitalium

### ISSUE THREAD

**Issue by aki-k** [DISTRHO/DISTRHO-Ports#73]
I'm using Ardour on Ubuntu Mate 18.04 using the nouveau kernel module for my Nvidia card. 

The whole Xorg locks up after using Vitalium LV2 plugin for a while. I can still play my MIDI keyboard and Vitalium produces sound but even the virtual consoles are out of reach at that point.

**Comment by falkTX** [comment]
This sounds like a nouveau related problem.

**Comment by aki-k** [comment]
Booting with nouveau.noaccel=1 resolved the system hangup but now just having the Vitalium GUI open causes a huge CPU spike. Decided to install the NVIDIA closed source driver and now these problems are gone.
