### ISSUE TITLE
Vitalium: Window view vertically offset from input under GNOME (lv2, Ardour)

### ISSUE THREAD

**Issue by mitchmindtree** [DISTRHO/DISTRHO-Ports#74]
Firstly, thanks for your speedy work on the Vitalium port! Exciting stuff :)

I just built distrho-ports using [this nix expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/distrho/default.nix) but updated to point to [the current master commit](https://github.com/DISTRHO/DISTRHO-Ports/commit/67cdebbd2472380ac5c4339ac82fba4749b0e6da). The build worked like a charm and the Vitalium plugin shows up in Ardour.

Oddly, the view of the plugin window (when run via Ardour) appears to be vetically offset from the actual input like so, making it particularly tricky to navigate the interface:

![vitalium-lv2-plugin-view-offset](https://user-images.githubusercontent.com/4587373/109966045-13bbc480-7cf0-11eb-8cf2-23a917bb0987.png)

Not sure exactly what's going on here, but for what it's worth this problem also occurs when running the standalone version of Vital itself:

![vital-standalone-view-offset](https://user-images.githubusercontent.com/4587373/109966403-8462e100-7cf0-11eb-97c5-4990339a6e61.png)

I wonder if perhaps this is specific to Vital/Vitalium within GTK windows? Curious to hear if anyone else has run into this or has any workarounds. Resizing the height exposes more of the UI from the top, but the view remains vertically offset from the actual mouse input by the height of the black bar at the bottom.

System info:

```
[mindtree@mindtree:~]$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.10, channels(root): "nixos-hardware, nixos-21.03pre259798.84917aa00bf, home-manager-20.09", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

[mindtree@mindtree:~]$ uname -r
5.10.18

[mindtree@mindtree:~]$ gnome-shell --version
GNOME Shell 3.38.2
```

Processor: 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz × 8
Graphics: Mesa Intel® Xe Graphics (TGL GT2)

**Comment by aki-k** [comment]
> Curious to hear if anyone else has run into this

Yes I also have that problem. It's like the offset is about 16 pixels or so, so I have to put the mouse cursor below the actual button I want to press.

**Comment by falkTX** [comment]
Yes, this has been reported in #68 already.
The ticket did not have the best title, I corrected that now.
Lets put all the discussion surrounding offset drawing on that ticket, thanks.
