### ISSUE TITLE
Vitalium no imports and new folder.

### ISSUE THREAD

**Issue by geekositalia** [DISTRHO/DISTRHO-Ports#77]
Hi, I'm joboschetti from geekosdaw project (suse), first of all congratulations for the excellent work.

Vitalium gives the known problem, opengl 1.4 not supported, but with a script:

#! / bin / bash
export MESA_GL_VERSION_OVERRIDE = 3.2
ardour6 (or ./reaper)

It works as it should on my machine.

The problem is that I don't care about the vitalbanks, nor can I create folders from the plugin to get my wavetables.

The workardound is to put everything by hand in .local / share / vitalium (both the factory vitalbank presets once extracted, and the wavetables, just insert them under user)

**Comment by falkTX** [comment]
your wording is confusing. you care about the vital bank stuff or not?
I am not allowed to redistribute the original presets, so vitalium comes without them. this is expected and will not change.

**Comment by geekositalia** [comment]
Sorry, the problem is import function not work (i testing with vital bank but i not expeted you redistribute), even, if i want select new folder for custom wavetables, not work, i need create them manually on .locale/share/vitalium

**Comment by geekositalia** [comment]
![Screenshot_20210306_181833](https://user-images.githubusercontent.com/55261197/110215120-64761d80-7ea8-11eb-9919-fd3833ff4c13.png)
this does not allow it, selected the folder does not appear, the same thing when importing banks from the import function

**Comment by falkTX** [comment]
and this is with the updated code from today?

on my system this tries to open dolphin in the presets folder.
does `xdg-open` with a folder work for you?

**Comment by geekositalia** [comment]
version from 2021/03/02

No problem for dolhin, navigate from folders, select, but... folder not appear on plugin after this

**Comment by falkTX** [comment]
Not sure I follow. I will let others comment on the subject in case they experience similar issues.

btw, please update the vitalium build, some fixes have been applied (today, a few hours ago).
It will not fix this exact issue though.

**Comment by geekositalia** [comment]
Perfect, i update latest version on our repository for audio on opensuse, and will work, no gl workaround, and folder selection not use external file manager, and work! All work okay, but lv2 crash if i close the plugin, and repone plugin windows, graphic glitches and crash. But other issue is open for this. Thanks! and.. very nice work.
