### ISSUE TITLE
I've got more Vitalium presets

### ISSUE THREAD

**Issue by unfa** [DISTRHO/DISTRHO-Ports#80]
I've dug up my Vital patch collection created in the past years, and I've sifted through that.

[Presets.zip](https://github.com/DISTRHO/DISTRHO-Ports/files/6135858/Presets.zip)

I'd love to add them to my bank of factory presets, though I don't know how to do that myself.

**Comment by falkTX** [comment]
See #81

It will help me a bunch by loading jalv and saving the presets from there.

Lets keep discussion in a single place, so I will close this ticket.
