### ISSUE TITLE
Standalone mode for vitalium?

### ISSUE THREAD

**Issue by kurtbusch420** [DISTRHO/DISTRHO-Ports#84]
I started using vital mainly because 
1. of the standalone
2. jack can be substituted with pulseaudio without any third party (jalv) assistance, like in odin2.

Is it possible to build the standalone version of vitalium using this repository?

**Comment by falkTX** [comment]
No, this is unsupported.

You can use the plugin in Carla which supports a pulseaudio backend.

**Comment by kurtbusch420** [comment]
Did Vital's author not release the code behind the standalone?

**Comment by falkTX** [comment]
JUCE provides that. I just dont enable such features on this repository.
Feel free to use any of the other forks that provide that.
